config/routes.rb
Rails.application.routes.draw do
  resources :petitions
  resources :logs
  resources :entry_houses
  resources :housing_schedules
  resources :languages
  resources :entry_people
  resources :household_schedules
  resources :addresses
  resources :officers
  resources :sub_districts
  resources :districts
  resources :states
  resources :census
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/censu.rb
class Censu < ApplicationRecord
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/entry_house.rb
class EntryHouse < ApplicationRecord
end

app/models/entry_person.rb
class EntryPerson < ApplicationRecord
end

app/models/household_schedule.rb
class HouseholdSchedule < ApplicationRecord
end

app/models/housing_schedule.rb
class HousingSchedule < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/officer.rb
class Officer < ApplicationRecord
end

app/models/petition.rb
class Petition < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/sub_district.rb
class SubDistrict < ApplicationRecord
end

app/controllers/household_schedules_controller.rb
class HouseholdSchedulesController < ApplicationController
  before_action :set_household_schedule, only: [:show, :edit, :update, :destroy]

  # GET /household_schedules
  # GET /household_schedules.json
  def index
    @household_schedules = HouseholdSchedule.all
  end

  # GET /household_schedules/1
  # GET /household_schedules/1.json
  def show
  end

  # GET /household_schedules/new
  def new
    @household_schedule = HouseholdSchedule.new
  end

  # GET /household_schedules/1/edit
  def edit
  end

  # POST /household_schedules
  # POST /household_schedules.json
  def create
    @household_schedule = HouseholdSchedule.new(household_schedule_params)

    respond_to do |format|
      if @household_schedule.save
        format.html { redirect_to @household_schedule, notice: 'Household schedule was successfully created.' }
        format.json { render :show, status: :created, location: @household_schedule }
      else
        format.html { render :new }
        format.json { render json: @household_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /household_schedules/1
  # PATCH/PUT /household_schedules/1.json
  def update
    respond_to do |format|
      if @household_schedule.update(household_schedule_params)
        format.html { redirect_to @household_schedule, notice: 'Household schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @household_schedule }
      else
        format.html { render :edit }
        format.json { render json: @household_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /household_schedules/1
  # DELETE /household_schedules/1.json
  def destroy
    @household_schedule.destroy
    respond_to do |format|
      format.html { redirect_to household_schedules_url, notice: 'Household schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_household_schedule
      @household_schedule = HouseholdSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def household_schedule_params
      params.require(:household_schedule).permit(:address, :form_number, :status, :enumeration_block_number, :enumeration_sub_block_number, :houselist_block_number, :serial_number, :type, :details, :population_m, :population_f, :population_o, :young_m, :young_f, :young_o, :literate_m, :literate_f, :literate_o, :illiterate_m, :illiterate_f, :illiterate_o, :respondent, :email, :phone, :enumerator, :supervisor, :filing_date, :census)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/census_helper.rb
module CensusHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/household_schedules_helper.rb
module HouseholdSchedulesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/officers_helper.rb
module OfficersHelper
end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/household_schedules/_form.html.erb
<%= form_with(model: household_schedule, local: true) do |form| %>
  <% if household_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(household_schedule.errors.count, "error") %> prohibited this household_schedule from being saved:</h2>

      <ul>
      <% household_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.number_field :address %>
  </div>

  <div class="field">
    <%= form.label :form_number %>
    <%= form.text_field :form_number %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :enumeration_block_number %>
    <%= form.text_field :enumeration_block_number %>
  </div>

  <div class="field">
    <%= form.label :enumeration_sub_block_number %>
    <%= form.text_field :enumeration_sub_block_number %>
  </div>

  <div class="field">
    <%= form.label :houselist_block_number %>
    <%= form.text_field :houselist_block_number %>
  </div>

  <div class="field">
    <%= form.label :serial_number %>
    <%= form.text_field :serial_number %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="field">
    <%= form.label :population_m %>
    <%= form.number_field :population_m %>
  </div>

  <div class="field">
    <%= form.label :population_f %>
    <%= form.number_field :population_f %>
  </div>

  <div class="field">
    <%= form.label :population_o %>
    <%= form.number_field :population_o %>
  </div>

  <div class="field">
    <%= form.label :young_m %>
    <%= form.number_field :young_m %>
  </div>

  <div class="field">
    <%= form.label :young_f %>
    <%= form.number_field :young_f %>
  </div>

  <div class="field">
    <%= form.label :young_o %>
    <%= form.number_field :young_o %>
  </div>

  <div class="field">
    <%= form.label :literate_m %>
    <%= form.number_field :literate_m %>
  </div>

  <div class="field">
    <%= form.label :literate_f %>
    <%= form.number_field :literate_f %>
  </div>

  <div class="field">
    <%= form.label :literate_o %>
    <%= form.number_field :literate_o %>
  </div>

  <div class="field">
    <%= form.label :illiterate_m %>
    <%= form.number_field :illiterate_m %>
  </div>

  <div class="field">
    <%= form.label :illiterate_f %>
    <%= form.number_field :illiterate_f %>
  </div>

  <div class="field">
    <%= form.label :illiterate_o %>
    <%= form.number_field :illiterate_o %>
  </div>

  <div class="field">
    <%= form.label :respondent %>
    <%= form.text_field :respondent %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :enumerator %>
    <%= form.number_field :enumerator %>
  </div>

  <div class="field">
    <%= form.label :supervisor %>
    <%= form.number_field :supervisor %>
  </div>

  <div class="field">
    <%= form.label :filing_date %>
    <%= form.datetime_select :filing_date %>
  </div>

  <div class="field">
    <%= form.label :census %>
    <%= form.number_field :census %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/household_schedules/edit.html.erb
<h1>Editing Household Schedule</h1>

<%= render 'form', household_schedule: @household_schedule %>

<%= link_to 'Show', @household_schedule %> |
<%= link_to 'Back', household_schedules_path %>

app/views/household_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Household Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Form number</th>
      <th>Status</th>
      <th>Enumeration block number</th>
      <th>Enumeration sub block number</th>
      <th>Houselist block number</th>
      <th>Serial number</th>
      <th>Type</th>
      <th>Details</th>
      <th>Population m</th>
      <th>Population f</th>
      <th>Population o</th>
      <th>Young m</th>
      <th>Young f</th>
      <th>Young o</th>
      <th>Literate m</th>
      <th>Literate f</th>
      <th>Literate o</th>
      <th>Illiterate m</th>
      <th>Illiterate f</th>
      <th>Illiterate o</th>
      <th>Respondent</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Enumerator</th>
      <th>Supervisor</th>
      <th>Filing date</th>
      <th>Census</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @household_schedules.each do |household_schedule| %>
      <tr>
        <td><%= household_schedule.address %></td>
        <td><%= household_schedule.form_number %></td>
        <td><%= household_schedule.status %></td>
        <td><%= household_schedule.enumeration_block_number %></td>
        <td><%= household_schedule.enumeration_sub_block_number %></td>
        <td><%= household_schedule.houselist_block_number %></td>
        <td><%= household_schedule.serial_number %></td>
        <td><%= household_schedule.type %></td>
        <td><%= household_schedule.details %></td>
        <td><%= household_schedule.population_m %></td>
        <td><%= household_schedule.population_f %></td>
        <td><%= household_schedule.population_o %></td>
        <td><%= household_schedule.young_m %></td>
        <td><%= household_schedule.young_f %></td>
        <td><%= household_schedule.young_o %></td>
        <td><%= household_schedule.literate_m %></td>
        <td><%= household_schedule.literate_f %></td>
        <td><%= household_schedule.literate_o %></td>
        <td><%= household_schedule.illiterate_m %></td>
        <td><%= household_schedule.illiterate_f %></td>
        <td><%= household_schedule.illiterate_o %></td>
        <td><%= household_schedule.respondent %></td>
        <td><%= household_schedule.email %></td>
        <td><%= household_schedule.phone %></td>
        <td><%= household_schedule.enumerator %></td>
        <td><%= household_schedule.supervisor %></td>
        <td><%= household_schedule.filing_date %></td>
        <td><%= household_schedule.census %></td>
        <td><%= link_to 'Show', household_schedule %></td>
        <td><%= link_to 'Edit', edit_household_schedule_path(household_schedule) %></td>
        <td><%= link_to 'Destroy', household_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Household Schedule', new_household_schedule_path %>

app/views/household_schedules/new.html.erb
<h1>New Household Schedule</h1>

<%= render 'form', household_schedule: @household_schedule %>

<%= link_to 'Back', household_schedules_path %>

app/views/household_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @household_schedule.address %>
</p>

<p>
  <strong>Form number:</strong>
  <%= @household_schedule.form_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @household_schedule.status %>
</p>

<p>
  <strong>Enumeration block number:</strong>
  <%= @household_schedule.enumeration_block_number %>
</p>

<p>
  <strong>Enumeration sub block number:</strong>
  <%= @household_schedule.enumeration_sub_block_number %>
</p>

<p>
  <strong>Houselist block number:</strong>
  <%= @household_schedule.houselist_block_number %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @household_schedule.serial_number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @household_schedule.type %>
</p>

<p>
  <strong>Details:</strong>
  <%= @household_schedule.details %>
</p>

<p>
  <strong>Population m:</strong>
  <%= @household_schedule.population_m %>
</p>

<p>
  <strong>Population f:</strong>
  <%= @household_schedule.population_f %>
</p>

<p>
  <strong>Population o:</strong>
  <%= @household_schedule.population_o %>
</p>

<p>
  <strong>Young m:</strong>
  <%= @household_schedule.young_m %>
</p>

<p>
  <strong>Young f:</strong>
  <%= @household_schedule.young_f %>
</p>

<p>
  <strong>Young o:</strong>
  <%= @household_schedule.young_o %>
</p>

<p>
  <strong>Literate m:</strong>
  <%= @household_schedule.literate_m %>
</p>

<p>
  <strong>Literate f:</strong>
  <%= @household_schedule.literate_f %>
</p>

<p>
  <strong>Literate o:</strong>
  <%= @household_schedule.literate_o %>
</p>

<p>
  <strong>Illiterate m:</strong>
  <%= @household_schedule.illiterate_m %>
</p>

<p>
  <strong>Illiterate f:</strong>
  <%= @household_schedule.illiterate_f %>
</p>

<p>
  <strong>Illiterate o:</strong>
  <%= @household_schedule.illiterate_o %>
</p>

<p>
  <strong>Respondent:</strong>
  <%= @household_schedule.respondent %>
</p>

<p>
  <strong>Email:</strong>
  <%= @household_schedule.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @household_schedule.phone %>
</p>

<p>
  <strong>Enumerator:</strong>
  <%= @household_schedule.enumerator %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @household_schedule.supervisor %>
</p>

<p>
  <strong>Filing date:</strong>
  <%= @household_schedule.filing_date %>
</p>

<p>
  <strong>Census:</strong>
  <%= @household_schedule.census %>
</p>

<%= link_to 'Edit', edit_household_schedule_path(@household_schedule) %> |
<%= link_to 'Back', household_schedules_path %>