config/routes.rb
Rails.application.routes.draw do
  resources :petitions
  resources :logs
  resources :entry_houses
  resources :housing_schedules
  resources :languages
  resources :entry_people
  resources :household_schedules
  resources :addresses
  resources :officers
  resources :sub_districts
  resources :districts
  resources :states
  resources :census
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/censu.rb
class Censu < ApplicationRecord
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/entry_house.rb
class EntryHouse < ApplicationRecord
end

app/models/entry_person.rb
class EntryPerson < ApplicationRecord
end

app/models/household_schedule.rb
class HouseholdSchedule < ApplicationRecord
end

app/models/housing_schedule.rb
class HousingSchedule < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/officer.rb
class Officer < ApplicationRecord
end

app/models/petition.rb
class Petition < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/sub_district.rb
class SubDistrict < ApplicationRecord
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:code, :name, :population, :area, :density)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/census_helper.rb
module CensusHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/officers_helper.rb
module OfficersHelper
end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :population %>
    <%= form.text_field :population %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area %>
  </div>

  <div class="field">
    <%= form.label :density %>
    <%= form.text_field :density %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>States</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Population</th>
      <th>Area</th>
      <th>Density</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.code %></td>
        <td><%= state.name %></td>
        <td><%= state.population %></td>
        <td><%= state.area %></td>
        <td><%= state.density %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @state.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Population:</strong>
  <%= @state.population %>
</p>

<p>
  <strong>Area:</strong>
  <%= @state.area %>
</p>

<p>
  <strong>Density:</strong>
  <%= @state.density %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>