config/routes.rb
Rails.application.routes.draw do
  resources :petitions
  resources :logs
  resources :entry_houses
  resources :housing_schedules
  resources :languages
  resources :entry_people
  resources :household_schedules
  resources :addresses
  resources :officers
  resources :sub_districts
  resources :districts
  resources :states
  resources :census
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/censu.rb
class Censu < ApplicationRecord
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/entry_house.rb
class EntryHouse < ApplicationRecord
end

app/models/entry_person.rb
class EntryPerson < ApplicationRecord
end

app/models/housing_schedule.rb
class HousingSchedule < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/officer.rb
class Officer < ApplicationRecord
end

app/models/petition.rb
class Petition < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/sub_district.rb
class SubDistrict < ApplicationRecord
end

app/controllers/housing_schedules_controller.rb
class HousingSchedulesController < ApplicationController
  before_action :set_housing_schedule, only: [:show, :edit, :update, :destroy]

  # GET /housing_schedules
  # GET /housing_schedules.json
  def index
    @housing_schedules = HousingSchedule.all
  end

  # GET /housing_schedules/1
  # GET /housing_schedules/1.json
  def show
  end

  # GET /housing_schedules/new
  def new
    @housing_schedule = HousingSchedule.new
  end

  # GET /housing_schedules/1/edit
  def edit
  end

  # POST /housing_schedules
  # POST /housing_schedules.json
  def create
    @housing_schedule = HousingSchedule.new(housing_schedule_params)

    respond_to do |format|
      if @housing_schedule.save
        format.html { redirect_to @housing_schedule, notice: 'Housing schedule was successfully created.' }
        format.json { render :show, status: :created, location: @housing_schedule }
      else
        format.html { render :new }
        format.json { render json: @housing_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /housing_schedules/1
  # PATCH/PUT /housing_schedules/1.json
  def update
    respond_to do |format|
      if @housing_schedule.update(housing_schedule_params)
        format.html { redirect_to @housing_schedule, notice: 'Housing schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @housing_schedule }
      else
        format.html { render :edit }
        format.json { render json: @housing_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /housing_schedules/1
  # DELETE /housing_schedules/1.json
  def destroy
    @housing_schedule.destroy
    respond_to do |format|
      format.html { redirect_to housing_schedules_url, notice: 'Housing schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_housing_schedule
      @housing_schedule = HousingSchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def housing_schedule_params
      params.require(:housing_schedule).permit(:address, :form_number, :status, :enumeration_block_number, :enumeration_sub_block_number, :houselist_block_number, :serial_number, :respondent, :email, :phone, :enumerator, :supervisor, :filing_date, :census)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/census_helper.rb
module CensusHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/housing_schedules_helper.rb
module HousingSchedulesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/officers_helper.rb
module OfficersHelper
end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/housing_schedules/_form.html.erb
<%= form_with(model: housing_schedule, local: true) do |form| %>
  <% if housing_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(housing_schedule.errors.count, "error") %> prohibited this housing_schedule from being saved:</h2>

      <ul>
      <% housing_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.number_field :address %>
  </div>

  <div class="field">
    <%= form.label :form_number %>
    <%= form.text_field :form_number %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :enumeration_block_number %>
    <%= form.text_field :enumeration_block_number %>
  </div>

  <div class="field">
    <%= form.label :enumeration_sub_block_number %>
    <%= form.text_field :enumeration_sub_block_number %>
  </div>

  <div class="field">
    <%= form.label :houselist_block_number %>
    <%= form.text_field :houselist_block_number %>
  </div>

  <div class="field">
    <%= form.label :serial_number %>
    <%= form.text_field :serial_number %>
  </div>

  <div class="field">
    <%= form.label :respondent %>
    <%= form.text_field :respondent %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :enumerator %>
    <%= form.number_field :enumerator %>
  </div>

  <div class="field">
    <%= form.label :supervisor %>
    <%= form.number_field :supervisor %>
  </div>

  <div class="field">
    <%= form.label :filing_date %>
    <%= form.datetime_select :filing_date %>
  </div>

  <div class="field">
    <%= form.label :census %>
    <%= form.number_field :census %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/housing_schedules/edit.html.erb
<h1>Editing Housing Schedule</h1>

<%= render 'form', housing_schedule: @housing_schedule %>

<%= link_to 'Show', @housing_schedule %> |
<%= link_to 'Back', housing_schedules_path %>

app/views/housing_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Housing Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Form number</th>
      <th>Status</th>
      <th>Enumeration block number</th>
      <th>Enumeration sub block number</th>
      <th>Houselist block number</th>
      <th>Serial number</th>
      <th>Respondent</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Enumerator</th>
      <th>Supervisor</th>
      <th>Filing date</th>
      <th>Census</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @housing_schedules.each do |housing_schedule| %>
      <tr>
        <td><%= housing_schedule.address %></td>
        <td><%= housing_schedule.form_number %></td>
        <td><%= housing_schedule.status %></td>
        <td><%= housing_schedule.enumeration_block_number %></td>
        <td><%= housing_schedule.enumeration_sub_block_number %></td>
        <td><%= housing_schedule.houselist_block_number %></td>
        <td><%= housing_schedule.serial_number %></td>
        <td><%= housing_schedule.respondent %></td>
        <td><%= housing_schedule.email %></td>
        <td><%= housing_schedule.phone %></td>
        <td><%= housing_schedule.enumerator %></td>
        <td><%= housing_schedule.supervisor %></td>
        <td><%= housing_schedule.filing_date %></td>
        <td><%= housing_schedule.census %></td>
        <td><%= link_to 'Show', housing_schedule %></td>
        <td><%= link_to 'Edit', edit_housing_schedule_path(housing_schedule) %></td>
        <td><%= link_to 'Destroy', housing_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Housing Schedule', new_housing_schedule_path %>

app/views/housing_schedules/new.html.erb
<h1>New Housing Schedule</h1>

<%= render 'form', housing_schedule: @housing_schedule %>

<%= link_to 'Back', housing_schedules_path %>

app/views/housing_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @housing_schedule.address %>
</p>

<p>
  <strong>Form number:</strong>
  <%= @housing_schedule.form_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @housing_schedule.status %>
</p>

<p>
  <strong>Enumeration block number:</strong>
  <%= @housing_schedule.enumeration_block_number %>
</p>

<p>
  <strong>Enumeration sub block number:</strong>
  <%= @housing_schedule.enumeration_sub_block_number %>
</p>

<p>
  <strong>Houselist block number:</strong>
  <%= @housing_schedule.houselist_block_number %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @housing_schedule.serial_number %>
</p>

<p>
  <strong>Respondent:</strong>
  <%= @housing_schedule.respondent %>
</p>

<p>
  <strong>Email:</strong>
  <%= @housing_schedule.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @housing_schedule.phone %>
</p>

<p>
  <strong>Enumerator:</strong>
  <%= @housing_schedule.enumerator %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @housing_schedule.supervisor %>
</p>

<p>
  <strong>Filing date:</strong>
  <%= @housing_schedule.filing_date %>
</p>

<p>
  <strong>Census:</strong>
  <%= @housing_schedule.census %>
</p>

<%= link_to 'Edit', edit_housing_schedule_path(@housing_schedule) %> |
<%= link_to 'Back', housing_schedules_path %>