config/routes.rb
Rails.application.routes.draw do
  resources :petitions
  resources :logs
  resources :entry_houses
  resources :housing_schedules
  resources :languages
  resources :entry_people
  resources :household_schedules
  resources :addresses
  resources :officers
  resources :sub_districts
  resources :districts
  resources :states
  resources :census
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/censu.rb
class Censu < ApplicationRecord
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/entry_house.rb
class EntryHouse < ApplicationRecord
end

app/models/entry_person.rb
class EntryPerson < ApplicationRecord
end

app/models/housing_schedule.rb
class HousingSchedule < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/officer.rb
class Officer < ApplicationRecord
end

app/models/petition.rb
class Petition < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/sub_district.rb
class SubDistrict < ApplicationRecord
end

app/controllers/sub_districts_controller.rb
class SubDistrictsController < ApplicationController
  before_action :set_sub_district, only: [:show, :edit, :update, :destroy]

  # GET /sub_districts
  # GET /sub_districts.json
  def index
    @sub_districts = SubDistrict.all
  end

  # GET /sub_districts/1
  # GET /sub_districts/1.json
  def show
  end

  # GET /sub_districts/new
  def new
    @sub_district = SubDistrict.new
  end

  # GET /sub_districts/1/edit
  def edit
  end

  # POST /sub_districts
  # POST /sub_districts.json
  def create
    @sub_district = SubDistrict.new(sub_district_params)

    respond_to do |format|
      if @sub_district.save
        format.html { redirect_to @sub_district, notice: 'Sub district was successfully created.' }
        format.json { render :show, status: :created, location: @sub_district }
      else
        format.html { render :new }
        format.json { render json: @sub_district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_districts/1
  # PATCH/PUT /sub_districts/1.json
  def update
    respond_to do |format|
      if @sub_district.update(sub_district_params)
        format.html { redirect_to @sub_district, notice: 'Sub district was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_district }
      else
        format.html { render :edit }
        format.json { render json: @sub_district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_districts/1
  # DELETE /sub_districts/1.json
  def destroy
    @sub_district.destroy
    respond_to do |format|
      format.html { redirect_to sub_districts_url, notice: 'Sub district was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_district
      @sub_district = SubDistrict.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_district_params
      params.require(:sub_district).permit(:name, :population, :area, :density, :district)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/census_helper.rb
module CensusHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/officers_helper.rb
module OfficersHelper
end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/sub_districts_helper.rb
module SubDistrictsHelper
end

app/views/sub_districts/_form.html.erb
<%= form_with(model: sub_district, local: true) do |form| %>
  <% if sub_district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_district.errors.count, "error") %> prohibited this sub_district from being saved:</h2>

      <ul>
      <% sub_district.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :population %>
    <%= form.text_field :population %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area %>
  </div>

  <div class="field">
    <%= form.label :density %>
    <%= form.text_field :density %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.number_field :district %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_districts/edit.html.erb
<h1>Editing Sub District</h1>

<%= render 'form', sub_district: @sub_district %>

<%= link_to 'Show', @sub_district %> |
<%= link_to 'Back', sub_districts_path %>

app/views/sub_districts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Districts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Population</th>
      <th>Area</th>
      <th>Density</th>
      <th>District</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_districts.each do |sub_district| %>
      <tr>
        <td><%= sub_district.name %></td>
        <td><%= sub_district.population %></td>
        <td><%= sub_district.area %></td>
        <td><%= sub_district.density %></td>
        <td><%= sub_district.district %></td>
        <td><%= link_to 'Show', sub_district %></td>
        <td><%= link_to 'Edit', edit_sub_district_path(sub_district) %></td>
        <td><%= link_to 'Destroy', sub_district, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub District', new_sub_district_path %>

app/views/sub_districts/new.html.erb
<h1>New Sub District</h1>

<%= render 'form', sub_district: @sub_district %>

<%= link_to 'Back', sub_districts_path %>

app/views/sub_districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_district.name %>
</p>

<p>
  <strong>Population:</strong>
  <%= @sub_district.population %>
</p>

<p>
  <strong>Area:</strong>
  <%= @sub_district.area %>
</p>

<p>
  <strong>Density:</strong>
  <%= @sub_district.density %>
</p>

<p>
  <strong>District:</strong>
  <%= @sub_district.district %>
</p>

<%= link_to 'Edit', edit_sub_district_path(@sub_district) %> |
<%= link_to 'Back', sub_districts_path %>